spring:
  profiles:
    active: dev

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  redisson:
    mode: single
    password: changeme
    nodes:
      - redis://localhost:6379

logging:
  level:
    org.redisson: debug
